$ANSIBLE_VAULT;1.1;AES256
66313830313630346631643861623537343932393663396633616131623064643330373038303130
6161393964303731343166343731616565343333373766360a356361653534666431376664386237
30316139353739626534303233353434323536323035643263363663303666346632663931396633
6534356565626565320a313532633539383935343537663262623835393932363738336164656138
35313330326463323664393663613763336333383832306135646139623862626239633763356661
34386338386539663731383132646362613239353563313566376232663866363862396637303938
33383863313165613761376639343139333838653962613964636537623231616530613334343066
65303130333731396131663838376635383133313736316337363562346531393432393939313764
61356264323333396166326231343330613961363632396337306262366131313635336334393266
39346536326639663834396131363431646632626637663463356264373331343033646330643161
66303966623630376338616366386564366336346534623337376363626164633961383037333965
65663762316630613336333465616661363566363763646331316234633335663936306636663839
33356233643765633030656263386365366136303765383938303337656631623438346365366261
3764343430393336623365346635356630316534353361333961
