$ANSIBLE_VAULT;1.1;AES256
38363964326136333630633163346137653133396231346666376137383466313830323361376336
3432366166343963396439663565636165373832653036340a383137643934623166313532613665
38366336633762623330386434343236623139343537333437336436613136373138613639383732
6533616633383632350a313334366466346365663735343633323962623134346338336334363531
66336365303033333934333638376466313038336132616561343238666530336535623061623831
3934393166663632633763376565336330353234393064666339
