apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meo-station-backend-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/minhtri1612/learning_RKE2.git
    targetRevision: HEAD
    path: k8s_helm/backend
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: meo-stationery
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true