apiVersion: v1
kind: Service
metadata:
  name: {{ include "database.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "database.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5432
    protocol: TCP
    name: postgres